<?php
class User {
    public $name;
    public $female;
    public $country;

    function __construct($n, $f, $c)
    {
        $this->name = $n;
        $this->female = $f;
        $this->country = $c;
    }

    function showInfo(){
        echo "<hr>";
        echo "Name: {$this->name} </br>";
        echo "Female: {$this->female} </br>";
        echo "Country: {$this->country} </br>";
    }
}

class SuperUser extends User{
    public $role;
    function __construct($n, $f, $c, $r)
    {
        parent::__construct($n, $f, $c);
        $this->role = $r;
    }
    function showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo "Role: {$this->role} </br>";
    }
}
$user1 = new User("John","Smith","UK");
$user1->showInfo();
$user2 = new SuperUser("Bob","Dilan","USA","Admin");
$user2->showInfo();